Repository SaiyamTuteja/Faculty_Evaluation_System, pull requests merged in 2024-05, with the labels that each got.

#10 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: gssoc, level1

#12 LEARN.md
  LEARN.md
  README.md
Labels: documentation, gssoc, level1

#26 logo added
  .vscode/settings.json
  login.php
  profpraisal.png
  signup.php
Labels: gssoc, level1

#47 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc, level1

#46 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: gssoc, level1

#40 Feat: Filter genuine email #21
  login.php
  process_signup.php
  signup.php
  verify_email.php
Labels: enhancement, gssoc, level2
